# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            TiDB Blog
tagline:          'TiDB Blog'
description:      'Inspired by Google Spanner/F1, PingCAP develops TiDB, an open source distributed Hybrid Transactional/Analytical Processing (HTAP) database.'
url:              https://github.io/pingcap/blog
baseurl:          ""
siteurl:          https://www.pingcap.com
excerpt_separator: "<!--more-->"

author:
  name:           'PingCAP'
  url:            https://www.pingcap.com

paginate:         5

# Custom vars
version:          Beta20160730

github:
  repo:           https://github.com/pingcap/tidb

weekly:
  url:            http://weekly.pingcap.com

