version: 2

jobs:
  lint:
    docker:
      - image: circleci/ruby:2.4.1-node
    working_directory: ~/pingcap/blog
    steps:
      - checkout

      - run:
          name: "Install markdownlint"
          command: |
            sudo npm install -g markdownlint-cli@0.17.0

      - run:
          name: "Lint README"
          command: markdownlint README.md

      - run:
          name: "Lint edited files"
          command: |
            git remote add upstream https://github.com/pingcap/blog.git
            git fetch upstream
            markdownlint $(git diff-tree --name-only --no-commit-id -r upstream/master..HEAD -- '*.md' ':(exclude).github/*')

            # unstable in circle ci, disable temporarily 
            #- run:
            #name: "Check links"
            #command: |
            #hack/verify-links.sh

workflows:
  version: 2
  lint:
    jobs:
      - lint
